### ISSUE TITLE
Add leaflet mapping to PlotMap*() functions

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#110]
Add an option to plot to a leaflet map to PlotMapOutput and PlotMapPoints. Resulting maps should provide

- the same choice of color mapping a current outputs
- a legend
- a standard selection of background maps
- a search for SUBIDs
- SUBID labels as optional layer choice
- other?

Some form of size check for the subbasin polygon map would be good, because leaflet map creation can take forever with large maps. At least mention in help that the map should be smallish/simplified.

**Comment by c-brendel** [comment]
I've found that using preferCanvas=T helps to speed up the map. Eg:

map=leaflet(options=leafletOptions(preferCanvas=T))%>%
  addTiles()%>%

**Comment by rcapell** [comment]
Interesting, thanks! I just ran a test and got a speed-up, but still ran into an error whith all ehype subbasins:
``` R
> saveWidget(m,file = "leaflet/map_ehype3_subbasin_checks_all_subbasins.html", title = "EHYPE3 domain")
Error: pandoc document conversion failed with error 9
```
The map was produced, though. The error seems to signify some form of out-of-memory comdition.

**Comment by c-brendel** [comment]
I had a problem saving widgets if I wasn't working on my local drive. If I was working on the network file server, then it couldn't find the files to create the HTML map. Not sure if that could be the cause for you too

**Comment by c-brendel** [comment]
> Interesting, thanks! I just ran a test and got a speed-up, but still ran into an error with all ehype subbasins:
> 
> ```r
> > saveWidget(m,file = "leaflet/map_ehype3_subbasin_checks_all_subbasins.html", title = "EHYPE3 domain")
> Error: pandoc document conversion failed with error 9
> ```
> 
> The map was produced, though. The error seems to signify some form of out-of-memory condition.

This issue occurs when saving self-contained HTML files. Specifying selfcontained = FALSE should fix the issue.
