### ISSUE TITLE
Problems with the WriteOptpar() function

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#112]
I'm failing to write the optpar file with the WriteOptpar() function. I passed a data.frame with a single ww-hype SLC parameters in 169 iand 3 columns.  I created the 'pars' list element as X[['pars']]$cevp = tx, where tx has 169 rows and 3 columns.

The list has the structure

``` R
str(X)
List of 3
 $ comment: chr "HUME WQ CALIBRATION"
 $ tasks  :'data.frame': 19 obs. of  2 variables:
  ..$ key  : chr [1:19] "task" "DEMC_ngen" "DEMC_npop" "DEMC_gammascale" ...
  ..$ value: chr [1:19] "DE" "100" "10" "0.6" ...
 $ pars   :List of 1
  ..$ cevp:'data.frame': 169 obs. of  3 variables:
  .. ..$ min : num [1:169] 0.17 0.17 0.17 0.05 0.07 0.07 0.07 0.07 0.07 0.07 ...
  .. ..$ max : num [1:169] 0.17 0.17 0.17 0.05 0.07 0.07 0.07 0.07 0.07 0.07 ...
  .. ..$ ival: num [1:169] 0.17 0.17 0.17 0.05 0.07 0.07 0.07 0.07 0.07 0.07 ...
```

In a text editor, the written file shows the data frame was not written to 3 rows with the parameter name at the beginning but rather

cevp
0.17
cevp
0.17
cevp
0.17
NA
0.05
NA
0.07
NA
0.07
NA ... etc

I tried passing the transposed df but that too didn't work.

**Comment by jmlubega** [comment]
Here are my steps and the stripped-down code 

X <- ReadOptpar(filename = file.path(dir.tmp, 'dummy-optpar.txt')) # read in sample optpar file for modification
X$comment = "HUME WQ CALIBRATION"
X$pars = X$pars[-2] #removed the second parameter from the list
names(X$pars) = 'cevp' # rename the remaining parameter
p=c(0.17, 0.17, 0.17, 0.05, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07) #Generate some parameter values
tx <- as.data.frame(matrix(rep(p, times=2), ncol=2, byrow = F )) #data frame with min/max parameter values (kept same here to save time)
tx[,3] <- rep(0.001, times=nrow(tx)) # increment value
colnames(tx) = c('min', 'max', 'ival')
X[['pars']]$cevp = tx #assign the list parameter values to the df
optparF = 'new_optpar.txt' #list output name
WriteOptpar(X, filename = optparF) #Writes the list to file without errors but the written content is wrong.

[dummy-optpar.txt](https://github.com/rcapell/HYPEtools/files/5957851/dummy-optpar.txt) #sample optpar read in at the beginning

**Comment by jmlubega** [comment]
Un truncated list I attempted but failed to write (generated following steps above):

dput(X)
list(comment = "HUME WQ CALIBRATION", tasks = structure(list(
    key = c("task", "DEMC_ngen", "DEMC_npop", "DEMC_gammascale", 
    "DEMC_crossover", "DEMC_sigma", "DEMC_accprob", "cal_log", 
    "task", "", "", "", "", "", "", "", "", "", ""), value = c("DE", 
    "500", "25", "0.8", "0.6", "1", "0.1", "y", "WA", "", "", 
    "", "", "", "", "", "", "", "")), class = "data.frame", row.names = c(NA, 
-19L)), pars = list(cevp = structure(list(min = c(0.17, 0.17, 
0.17, 0.05, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 
0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.21, 0.21, 0.21, 
0.21, 0.21, 0.17, 0, 1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 
0.22, 1.9, 1.9, 0.17, 0, 0.17, 0.17, 0, 0.17, 0.17, 0.17, 0.17, 
0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 0.21, 0.21, 0.17, 0, 1.6, 1.6, 
1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 1.9, 1.9, 0.17, 0, 0.17, 
0.17, 0, 0.17, 0.17, 0.17, 0.17, 0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 
0.21, 0.21, 0.17, 0, 1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 
0.22, 1.9, 1.9, 0.17, 0, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 
0.17, 0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 0.21, 0.21, 0.17, 1.6, 
1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 1.9, 1.9, 0.17, 
0.17, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 0.17, 0.1, 0.1, 0.1, 
0.21, 0.21, 0.21, 0.21, 0.17, 1.6, 1.6, 1.6, 1.6, 0.22, 0.22, 
1.9, 1.9, 0.17, 0.17, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 0.1, 
0.1, 0.1, 0.23, 0.23, 0.23, 0.23, 0.23), max = c(0.17, 0.17, 
0.17, 0.05, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 
0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.21, 0.21, 0.21, 
0.21, 0.21, 0.17, 3, 1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 
0.22, 1.9, 1.9, 0.17, 3, 0.17, 0.17, 3, 0.17, 0.17, 0.17, 0.17, 
0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 0.21, 0.21, 0.17, 3, 1.6, 1.6, 
1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 1.9, 1.9, 0.17, 3, 0.17, 
0.17, 3, 0.17, 0.17, 0.17, 0.17, 0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 
0.21, 0.21, 0.17, 3, 1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 
0.22, 1.9, 1.9, 0.17, 3, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 
0.17, 0.1, 0.1, 0.1, 0.21, 0.21, 0.21, 0.21, 0.21, 0.17, 1.6, 
1.6, 1.6, 1.6, 0.22, 0.22, 0.22, 0.22, 0.22, 1.9, 1.9, 0.17, 
0.17, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 0.17, 0.1, 0.1, 0.1, 
0.21, 0.21, 0.21, 0.21, 0.17, 1.6, 1.6, 1.6, 1.6, 0.22, 0.22, 
1.9, 1.9, 0.17, 0.17, 0.17, 0.17, 0.07, 0.17, 0.17, 0.17, 0.1, 
0.1, 0.1, 0.23, 0.23, 0.23, 0.23, 0.23), ival = c(0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.001, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.001, 0.005, 0.005, 0.001, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.001, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.001, 0.005, 0.005, 0.001, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.001, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.001, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 
0.005, 0.005, 0.005, 0.005, 0.005)), row.names = c(NA, -169L), class = "data.frame")))

**Comment by rcapell** [comment]
Should be solved now. Your file is a special case in that all parameters have the same number of values. Ok, not _that_ special, but something I did not test when writing the function :blush:. It caused a simplified result from `sapply` with the usual detrimental consequenses down the line... 

I also fixed the export of the optpar settings section, so one does not need to add empty rows to the `$tasks`data frame anymore.

Can you test and close this issue if you are happy with the result? Either using the latest master or offline using the updated function: 

``` R
WriteOptpar <- function (x, filename = "optpar.txt", digits = 10, nsmall = 1) {
  
  # convert all data frames in x$pars to lists of vectors and then flatten list of lists to list with vector elements
  px <- unlist(lapply(x$pars, as.list), recursive = FALSE)
  # format list contents to avoid scientific format in output
  px <- lapply(px, format, digits = digits, nsmall = nsmall, scientific = F, drop0trailing = T, trim = T, justify = "none")
  # add parameter names in first position of vector elements
  px <- lapply(1:length(px), function(x, y, z) {c(y[x], z[[x]])}, y = rep(names(x$pars), each = 3), z = px)
  
  # create and open file device
  out <- file(description = filename, open = "w")
  
  # write comment row
  writeLines(text = x$comment, con = out)
  
  # write optimisation settings
  write(apply(x$tasks, 1, paste, collapse = "\t"), file = out)
  
  # write empty lines to fill optimisation settings section (static section in optpar file, line 2 to 21)
  if (nrow(x$tasks) < 20) {
    empty <- rep("", 20 - nrow(x$tasks))
    writeLines(empty, con = out)
  }
  
  # write parameter ranges
  write(sapply(px, paste, collapse = "\t"), file = out)
  close(out)
  
}
```

**Comment by jmlubega** [comment]
This works! Thank you very much!
