### ISSUE TITLE
add possibility to read classgroup basinfiles

### ISSUE THREAD

**Issue by cpers** [rcapell/HYPEtools#113]
I would like to be able to read classgroup basinfiles. They have a comment row that ordinary basinfiles do not.
[0025814_DD_fora.txt](https://github.com/rcapell/HYPEtools/files/6076610/0025814_DD_fora.txt)

**Comment by rcapell** [comment]
Class output can also be written to time files. Check also if they have additional header rows.

**Comment by cpers** [comment]
Added an example classgroup timefile.
[timeCRUN_DD_CG1.txt](https://github.com/rcapell/HYPEtools/files/6091439/timeCRUN_DD_CG1.txt)

**Comment by rcapell** [comment]
Thanks Lotta!

I actually didn't mean to say that you should provide an example, it was more meant like a note to myself. Very helpful, though. :smile: 

Now I have some actual follow-up questions for you:

1. Both headers look different, the time file being in the new structured key=value format (which is in the HYPEtools implementation list, see #111). Will the basin file-header structured the same in a coming HYPE release?
2. Can I expect that all key-value pairs always exist in a time/map output file, even if there is no content? E.g., will there be a `SLCclasses=NA` pair, if the file does contain regular or region output, not class group output?
3. Following up from 2., what is the placeholder value (`NA` in my example), if the the key-value printing is fixed?
4. If 2. is true, will there be a key for region outputs as well (currently, all relevant import functions distinguish between normal and region by checking the filename or the HYPE variable IDs)?
5. What is the separator for multiple values in `SLCclasses`? Your example time file contains one value. Jugding from the basin file example, I guess it is a blank, but I want to make sure...

On a more general note, I wonder if we should merge all HYPEtools import functions into a single `ReadHypeOutput` function, and let the function extract all necessary import infos from the metadata header row. The would be more elegant, easier to maintain (lot of error-prone decision-making atm based on specific file properties, and the decision tree just keeps growing). For that, we would need complete and consistent metadata headers though, across all output files (or all we want to include, load files, e.g., I would keep separate to begin with).

We should discuss this at some point, and make a decision (and create a separate ticket, if we want to go ahead with it). For the moment, I will try and create a fix with the current structure.

**Comment by rcapell** [comment]
Functions work now with comment header rows (time file import does not use the information yet, though). 

@cpers Can you compile HYPEtools yourself for testing (using devtools and Rtools)? Otherwise, I can compile a windows binary as soon as I have access to a windows machine..
