### ISSUE TITLE
Sub-basin polygon simplification for using leaflet plotmapdata?

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/HYPEtools#118]
Hi
I am testing the leaflet mapping and understand that you made some sub-basin simplification in order to speed it up. 

What was the tool again, that you used for that simplification, and is there some recommendation on how to use it?

/David

**Comment by c-brendel** [comment]
Hi David,

Here is the tool I used for the sub-basin simplification:
https://github.com/mbloch/mapshaper

For EHYPE I installed mapshaper and then ran the following command to keep 0.1% of the vertices:
$ mapshaper-xl <input.shp> -simplify 0.1%  keep-shapes -o <output.shp>

Conrad

**Comment by dgustafsson** [comment]
Thanks Conrad,
I will try out the website first https://mapshaper.org/ before installing it. Looks quite smooth.
/David

**Comment by dgustafsson** [comment]
Rene, is it mandatory to import the polygons using the sf package now? or will it still work using readOGR?

**Comment by c-brendel** [comment]
You should still be able to use readOGR! I prefer the sf package, so I used that in my demonstration script.

**Comment by dgustafsson** [comment]
Thanks Conrad, I will close this issue now - produced my first interactive map with Yakutia HYPE. It's a great tool. Thanks a lot!

I tried simplification from 50%-0.1% Around 10% seems to preserve the original shape quite well - the 0.1% i would mainly use for fast production. /David

**Comment by dgustafsson** [comment]
do you also have some more examples with adding markers (such as you SMHI example).

Would it for instance be possible to add points for specific sub-basins with links to time series plots?

**Comment by c-brendel** [comment]
Hi David,

These resources provide a bunch of examples of cool things you can do with Leaflet in R!
https://rstudio.github.io/leaflet/
https://r-spatial.github.io/mapview/index.html

To add points for specific subbasins you could use the addMarkers() or addCircleMarkers() functions.
If you've already generated timeseries plots and saved them as files, then you could try using popup = popupImage()

`  addMarkers(
    group = "Doge",
    lng = 11.888990,
    lat = 57.684810,
    popup = popupImage("images/doge.jpg", src = "local", embed = T) # Add image popup
  )`

I'll add the example to the demonstration script

**Comment by dgustafsson** [comment]
If I plot several maps from the same model, it seems a bit redundant to export the subfolder with all the js files etc for each of the html-files, but maybe it's by design?

**Comment by c-brendel** [comment]
Yeah, that's just how the function to export the maps to HTML works. You can try changing the argument selfcontained to TRUE, and it will create one HTML file without the folder for the JavaScript files. However, this can be kind of buggy with paths and for larger maps

**Comment by rcapell** [comment]
Assuming you're plotting to a non-leaflet file, could you add this with mtext()? mtext allows line breaks...


________________________________
Från: dgustafsson ***@***.***>
Skickat: den 18 maj 2021 15:29
Till: rcapell/HYPEtools
Kopia: Capell René; Assign
Ämne: Re: [rcapell/HYPEtools] Sub-basin polygon simplification for using leaflet plotmapdata? (#118)


any ideas how to wrap the legend title on serveral rows? Or to get additional information into the figure somewhere?

I tried this, but it didnt work:
legend.title = paste("Yakutia-HYPE v2.0 \n Forecast day 1-2 \n Issue date ",runIssueDate," \n ","Q(m3/s)",sep="")

**Comment by dgustafsson** [comment]
no this was a leaflet plot - otherwise mtext would be a good solution.

**Comment by c-brendel** [comment]
You can use <br> to add the line breaks!

**Comment by dgustafsson** [comment]
I have some problems to control the color scale in PlotMapOutput:

PlotMapOutput(x = snow.trend.ann
+                 ,map = subshp
+                 ,map.subid.column = 2
+                 ,map.type = "leaflet"
+                 ,legend.title = "SWE-ANNUAL-MAX (mm/yr)"
+                 ,legend.pos = "bottomleft"
+                 ,col=ColDiffGeneric(5)
+                 ,col.breaks = c(-5,-1,-0.5,0.5,1,5)
+                 ,col.rev = FALSE
+                 ,legend.signif = 2)
Error in `levels<-.factor`(`*tmp*`, value = col) : 
  number of levels differs


Any ideas what it could be?

**Comment by rcapell** [comment]
Closing again, original issue was solved.
