### ISSUE TITLE
ReadPTQobs needs to know there are more inputs to HYPE than P, T and Q

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/HYPEtools#124]
latest version of ReadPTQobs throws and error if filename is not Pobs, Tobs or Qobs, but HYPE accept much more variables as input in the same file format, so maybe the function should recognise these as well? The variable argument also just accept temp, prec, and rout, but why dont just leave it open to any variable - doesnt even have to be an official HYPE variable? The function is handy to ready in anything on the same format. 

Currently, I am trying to read TMIN, TMAX, VW and UW, but we also have RH. SF, SW, and U-obs files read by HYPE. Not all of these have corresponding 4-letter hype variable names though, but we can always create our own for HYPEtools, for instance:

TMIN, tmin
TMAX, tmax
VW, vwnd
UW uwnd
SF snff
SW swrd (HYPE variable crgl calculated global radiation will be replaced by SWobs if it is provided)
RH rhum
U wind

See full description here:

http://www.smhi.net/hype/wiki/doku.php?id=start:hype_file_reference#observation_data_files

**Comment by rcapell** [comment]
Agreed. I lean towards renaming the function to `ReadObs`. Thanks for the variable name suggestions!

**Comment by rcapell** [comment]
Ready for testing, function name changed to ReadObs, with ReadPTQobs alias for backwards compatibility.
@dgustafsson Please close the issue if the updated function works for you.
