### ISSUE TITLE
New function suggestion - model performance by land use etc

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#126]
It would be great to have a function for "Johan's calibration plots" where he analyzes model performance by various catchment characteristics like in this example:

![image](https://user-images.githubusercontent.com/20319028/139281728-dc867770-08fc-4c01-be19-aa5d8cae71ce.png)

(He might have been using the rescaled RE in this figure or just limited the scale to +-100%, not sure which)

**Comment by c-brendel** [comment]
Features added with commit cdf927709c906fa1dd5d89b31845a211a376caab
