### ISSUE TITLE
Error in fread during the ReadWsOutput function. 

### ISSUE THREAD

**Issue by MaartenWynants** [rcapell/HYPEtools#129]
I encounter an error when trying to read in the data from calibrations. 
My code is:
basinoutputs<-ReadWsOutput(path=getwd(),type ="basin", id=1, dt.format="%Y-%m-%d",hype.var = "cout")

The following error pops up:
_|+++++++++++++++++++++++++                         | 50% ~00s          Error in fread(filename, na.strings = c("-9999", "****************", "-1.0E+04",  : 
  skip=3 but the input only has 3 lines_

I have 5 "basin files" and none of them has -9999 values. 
Any help would be appreciated!

Regards,
Maarten

**Comment by rcapell** [comment]
Hi Maarten, thanks for your report. Could you attach the basin files you are trying to read? Best, René

**Comment by MaartenWynants** [comment]
[0000001_001.txt](https://github.com/rcapell/HYPEtools/files/8372310/0000001_001.txt)
[0000001_002.txt](https://github.com/rcapell/HYPEtools/files/8372311/0000001_002.txt)
[0000001_003.txt](https://github.com/rcapell/HYPEtools/files/8372313/0000001_003.txt)
[0000001_004.txt](https://github.com/rcapell/HYPEtools/files/8372314/0000001_004.txt)
[0000001_005.txt](https://github.com/rcapell/HYPEtools/files/8372315/0000001_005.txt)

**Comment by rcapell** [comment]
Works for me with HYPEtools master, data.table 1.14.2, and R 4.1.3. What HYPEtools and data.table versions do you use?

**Comment by MaartenWynants** [comment]
I use data.table 1.14.2 and HYPEtools (not master?) 0.5.1. within R 4.1.2. I updated R to 4.1.3, but it did not change the error. 
I can read all the basinoutput files seperately using the ReadBasinOutput function. Replacing it with the full path did not change the error either. 
However, when I put the basinoutput files in a seperate folder, it did work. Not sure what the issue is here ... Maybe because I ran the entire WA as task?

**Comment by rcapell** [comment]
Hm, interesting. Sounds like the pattern matching to identify target files fails with the files you have in your original folder.
Can you try this and let me know if the results include other than the five SUBID 1 basin output files?
``` R
# either getwd or path string to the dir with which the error occurs
id <- 1
locs <- list.files(path = getwd(), pattern = glob2rx(paste0("*", id, "_", "*.txt")), full.names = TRUE)
locs
rm(id, locs)
```

**Comment by MaartenWynants** [comment]
Aha, yes it also includes the 5 subass1 files.

**Comment by rcapell** [comment]
Ok, then it is a bug. Nice catch! :smiley: 
Can you confirm that this line fixes the problem:
``` R
list.files(path = path, pattern = paste0("^[0]*", id,  "_.*\\.txt$"), full.names = TRUE)
```

**Comment by dgustafsson** [comment]
I think it could be useful if the pattern matching for HYPE variables could be turned off. Sometimes I use the HYPE data format for other types of data - just for the convenience of using the same format - but since you introduced this pattern matching I need to provide a fake variable name that is accepted by the import functions. Maybe consider an option to turn it off completely?

**Comment by rcapell** [comment]
@dgustafsson I'll open a new issue for that, easier to track progress then...

**Comment by MaartenWynants** [comment]
> Ok, then it is a bug. Nice catch! 😃 Can you confirm that this line fixes the problem:
> 
> ```r
> list.files(path = path, pattern = paste0("^[0]*", id,  "_.*\\.txt$"), full.names = TRUE)
> ```
Hi,
Using the trace function:
>trace("ReadWsOutput",edit=TRUE)
I managed the line of code and it works afterworks. 
When plotting the data, I noticed that the dates are saved as a character, prohibiting the plotting. However, that was easy to fix using the as.Date function afterwards. 

>basinoutputs<-ReadWsOutput(path=getwd(),type ="basin", id=0000001)  
>dim(basinoutputs); dimnames(basinoutputs)
>date<-as.Date(attr(basinoutputs,"datetime"))

**Comment by rcapell** [comment]
Thanks, I'll close this then!
Regarding date formatting: I didn't specify `date.format = "%F` in the function, default value is `NULL'  which leaves the string untouched. :smiley:
