### ISSUE TITLE
Option to disable pattern matching of HYPE file names in ReadWsOutput

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#130]
I think it could be useful if the pattern matching for HYPE variables could be turned off. Sometimes I use the HYPE data format for other types of data - just for the convenience of using the same format - but since you introduced this pattern matching I need to provide a fake variable name that is accepted by the import functions. Maybe consider an option to turn it off completely?

_Originally posted by @dgustafsson in https://github.com/rcapell/HYPEtools/issues/129#issuecomment-1082121731_

**Comment by dgustafsson** [comment]
In the case of ReadWSOutput, the files should most likely been produced b ythe HYPE model, so it would be a rare event (but not impossible) that a development-version of HYPE code is used including new HYPE variables that are not yet listed in the wikipages. 

More often I think, it is an issue for using the ReadTimeOutput, ReadXobs or ReadPTQobs functions. 

Maybe it would be possible for all of these functions, to add as a new argument a vector of additional HYPE variable IDs to consider (so not an exclusive list of files to read, but rather additional variable names to consider in addition to the variables in the wiki page?)

**Comment by dgustafsson** [comment]
it would be a minimum of modification of the code, just extend the list of variable ids with the new argument

**Comment by dgustafsson** [comment]
if(!is.null(newargument)){ varids = c(varids,newargument) }

**Comment by rcapell** [comment]
ReadObs (previously ReadPTQobs) now accepts any variable name in argument `variable`. Default behaviour is to try and extract from file name, and asign `"other"` as variable attribute if that fails.
I don't think there is any problem with ReadTimeOutput and ReadXobs (argument `hype.var` resp. `variable` which can be set to any value for those). If I am not mistaken...
