### ISSUE TITLE
error when run hype.exe

### ISSUE THREAD

**Issue by Nicole-X** [rcapell/HYPEtools#132]
![1653304336(1)](https://user-images.githubusercontent.com/74941596/169807074-34578908-19fa-4d8d-b73d-b4c6531cbaf5.jpg)

After I finished compiling the txt file and building the model, I clicked to run the HYPE.exe and then this error occurred(as shown in the figure). There were only timeXXXX and basin result file, but there was no data in it. Moreover, no mapXXXX file was generated. But there was no error in running demo files on the HYPE official website. 

Does anyone know what direction I could take to solve this problems?

**Comment by rcapell** [comment]
Hi, can I please redirect you to the HYPE forum at https://sourceforge.net/p/hype/discussion/ ? Here, we track issues with the HYPEtools pre/postprocessing package :)
Thanks!
René

**Comment by Nicole-X** [comment]
okay, thanks for redirecting :)
