### ISSUE TITLE
PlotBasinSummary() doesn't  export plot when using log scale and BasinOutput has column with all zero values

### ISSUE THREAD

**Issue by c-brendel** [rcapell/HYPEtools#134]
[0038649.txt](https://github.com/rcapell/HYPEtools/files/9076152/0038649.txt)

When ccSS and ccTS columns are all 0 then I get the following error when plotting with a log scale:
Error in plot.window(...) : need finite 'ylim' values

This error doesn't occur if I set the ccSS and ccTS columns to all NA values (-9999)

**Comment by rcapell** [comment]
Above commit makes the function proceed. 
Log scale exception treatment is a bit all over the place in PlotBasinSummary and plot function used within. I think the function tries a bit too hard to handle exceptions just now. Exceptions are:

1. No data at all (all NA)
2. All data NA or <= 0
3. Some but not all data <= 0

Exception handling is spread over the if-else-decision trees for cases with sim, obs, or both data. The warnings thrown during exception handling are mostly not helpful.

Proposal: If log scaled y axis is requested, we preprocess 'x' by replacing all values <= 0 with NA and throw a single warning to report that pruning. Then we don't need to check for every plot panel.

**Comment by rcapell** [comment]
Zero values in combination with log-scales can have other weird side effects as well, see #61
