### ISSUE TITLE
Error: object 'quartz' is not exported by 'namespace:grDevices'

### ISSUE THREAD

**Issue by c-brendel** [rcapell/HYPEtools#136]
In PlotBasinOutput() and PlotBasinSummary() the function quartz() is used to display plots on Darwin systems. However, this function is not included in grDevices on Windows, so I cannot build/install the HYPEtools package if "quartz" is listed as a dependency... when I try to build HYPEtools on Windows then I get the following error:

Error: object 'quartz' is not exported by 'namespace:grDevices'

**Comment by rcapell** [comment]
Seems to be a fallout of the explicit "import from" for libraries which are installed with base R anyway. When I did "Check package..." from RStudio's "Build" menu, I got notes for not declaring imports for these package. CRAN upload runs smoothest if there are no notes left on R Check. I think the workaround is good, would be interesting to see if you get a note with Check. If not, I vote for closing the issue  :smiley:

**Comment by c-brendel** [comment]
I see that you previously used dev.new(), but then in commit 825c5d1807ff503447f1b346a820a30d9f1868ef you switched to a OS specific approach. Do you remember why?

**Comment by rcapell** [comment]
Now I checked a bit: `dev.new()` triggers a pdf device under (my) linux. So maybe a workaround is to add device names (X11, quartz) explicitly as argument values? For now I don't know how to open a screen device with dev.new though...
Needs more testing but is not a critical bug because plotting to file is preferred anyway.

**Comment by c-brendel** [comment]
Could you maybe use getOption("device") to identify the default device type, then do options("device") = <device type>, and then do dev.new()?

**Comment by c-brendel** [comment]
> Now I checked a bit: `dev.new()` triggers a pdf device under (my) linux. So maybe a workaround is to add device names (X11, quartz) explicitly as argument values? For now I don't know how to open a screen device with dev.new though... Needs more testing but is not a bug which should stop the next release because plotting to file is preferred anyway.

See here about default devices:
https://stat.ethz.ch/R-manual/R-patched/RHOME/library/base/html/options.html
"The value of this option defaults to the normal screen device (e.g., X11, windows or quartz) for an interactive session, and pdf in batch use or if a screen is not available."

**Comment by rcapell** [comment]
Fixed as suggested, works nicely!
