### ISSUE TITLE
Create HYPEtools hexagon logo

### ISSUE THREAD

**Issue by c-brendel** [rcapell/HYPEtools#140]
The hexSticker package might help!
https://nanx.me/blog/post/rebranding-r-packages-with-hexagon-stickers/

**Comment by dgustafsson** [comment]
Could you add a tool to generate hexagonal subbasin polygons also? Covering a selected area of interest.
David


Den 8 nov. 2022 15:48 skrev c-brendel ***@***.***>:

The hexSticker package might help!
https://nanx.me/blog/post/rebranding-r-packages-with-hexagon-stickers/

**Comment by rcapell** [comment]
> Could you add a tool to generate hexagonal subbasin polygons also? Covering a selected area of interest. David 

https://stackoverflow.com/questions/29374004/how-do-i-generate-a-hexagonal-grid-in-r
=> should be doable, yes. Different topic though :smile:
