### ISSUE TITLE
Question about Plotbasinoutput date labels

### ISSUE THREAD

**Issue by MaartenWynants** [rcapell/HYPEtools#146]
Hi,

I noticed that when plotting dataseries under 1 year, the year does not show on the label (see attached). Is there a way to show both the months like on the figure, but also the years? I have been looking in the source code, but can't seem to pinpoint the code to change this.
![plot_Q_bas2](https://github.com/rcapell/HYPEtools/assets/22454715/75cfeab7-1043-468a-b645-d8331b6792c9)

**Comment by c-brendel** [comment]
Hi Maarten,

The plots are created using the base R plots, so I think the labels use the default formatting. If you want to change the formatting, I think you would need to add some code to lines 413-457 of the function_PlotBasinOutput.R file to format the axis using the axis() or axis.Date() functions.

I found some examples here:
https://stackoverflow.com/questions/4843969/plotting-time-series-with-date-labels-on-x-axis
https://stackoverflow.com/questions/24481176/r-x-axis-date-labels-using-plot

**Comment by MaartenWynants** [comment]
I managed to add a bit of code to the accumulated volume error of Q plot, stipulating an axis.posixCT.  
```r
 # accumulated volume error of Q
  if (exi.t["cout"] && exi.t["rout"] && vol.err) {
    
    # fill layout matrix with panel IDs
    lay.mat <- rbind(lay.mat, rep(if (suppressWarnings(expr = max(lay.mat)) == -Inf) {1} else {max(lay.mat) + 1}, 3)) 
    # add layout height for this row
    lay.heights <- c(lay.heights, 1)
    
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'par(mar = c(0, 3.6, 0, 0.5), xaxs = "i", mgp = c(2.2, .2, 0), tcl = .2, las = 1)')
    
    sqsim <- ConvertDischarge(q = get("cout"), area = uarea, from = "m3s", to = "mmd")
    sqobs <- ConvertDischarge(q = get("rout"), area = uarea, from = "m3s", to = "mmd")
    accvolerr <- cumsum(sqsim - ifelse(is.na(sqobs), sqsim, sqobs))
    
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'plot(date, accvolerr, type = "l", col = NA, xaxt = "n", ylab = "mm", cex.axis = 1.2, cex.lab = 1.5)')
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'abline(h = 0, col = "grey", lwd = .5)')
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'axis.POSIXct(1,date,at=seq(min(date), max(date), by="3 mon"), format="%b %Y")')
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'abline(v = date[which(format(date, format = "%m%d") == "0101")], , col = "grey", lwd = .5)')
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'lines(date, accvolerr, col = "seagreen")')
    cp <- cp + 1
    list.plotexpr[[cp]] <- parse(text = 'mtext(" Accumulated volume error", side=3, adj= 0, line=-1.1, cex = 1)')
```
However, the original monthly dating is still there, even though xact= "n". I am not sure where these other x axis dates are coming from. 
![plot_Q_bas2](https://github.com/rcapell/HYPEtools/assets/22454715/81cb36a1-4833-436d-be42-5043b5bc7d0b)

**Comment by c-brendel** [comment]
Hi Maarten,

I found the line of code to update the date format! It was farther down in the code, so my original instructions to you were wrong :( Anyway, I've now added a "date.format" argument to the function which will let you specify the format you'd like to use for the x-axis labels. You can grab the updated function_PlotBasinOutput.R file from the repo, but I'm planning to release a new version of HYPEtools to CRAN later today that will contain the update.
