### ISSUE TITLE
Update ScalePar function

### ISSUE THREAD

**Issue by c-brendel** [rcapell/HYPEtools#147]
The function currently applies the time-step scaling for exponential parameters, but there should be some sort of transformation/conversion to the exponential paramter values before the time-step scaling is applied.

Also, in HYPE v5.25.0 and earlier, the snowdensdt parameter is actually hard coded to be daily instead of being time-step dependent. So, this parameter shouldn't be scaled when updating models now. It's unclear when the parameter may be updated to be time-step dependent.

Finally, for threshold parameters (e.g. mperc), simple time-step scaling may not be optimal because e.g. dividing by 24 to go from a daily to hourly timestep results in lower thresholds that get exceeded more often and thus trigger certain processes more frequently

**Comment by rcapell** [comment]
Hidden recession coefficients to maybe consider as well:

- _gratk_, general rating curve for lakes. The rating curve has a power coefficient _gratp_ as well which may complicate translation
- _ilratk, olratk_, replace _gratk_ for ilakes/olakes in ilake/olake regions, if any. There is also a power coefficient
- _wetrate_, rating curve for wetlands, they work like lakes


In LakeData.txt and DamData.txt: _rate_

In AquiferData.txt: _retrate_

**Comment by c-brendel** [comment]
> Hidden recession coefficients to maybe consider as well:
> 
> * _gratk_, general rating curve for lakes. The rating curve has a power coefficient _gratp_ as well which may complicate translation
> * _ilratk, olratk_, replace _gratk_ for ilakes/olakes in ilake/olake regions, if any. There is also a power coefficient
> * _wetrate_, rating curve for wetlands, they work like lakes
> 
> In LakeData.txt and DamData.txt: _rate_
> 
> In AquiferData.txt: _retrate_

It seems like the gratk, ilratk, olratk, wetrate, and rate coefficients aren't limited to the range 0-1, so  the scaling doesn't really work with them. Lotta also says that they don't really have units of per timestep; they have units of more m/s (if exp = 2). I've added information to the help text as well as a warning message in ScalePar() about these coefficients. Lotta's recommendation is to check the results from lakes/wetlands and recalibrate these coefficients if needed.

**Comment by c-brendel** [comment]
Commits addressing this issue:
6e3181118164a436162d568be2d2541ae367f8b5
cc06733dc552a2f0d3ae988b3e7a8fce87b159b5
0d75b8eb9896fb7f641f49ec216f0c96ed052ebe
b3f59ad86efcfb01407302eb1319ad19f65007d8
b009e0b0b0d0c749baa40a18782b026604091b05
ae02c6475ff96865f9476006108e168046bc5e68
78bdc90ab75aaaa1e822c88df014dd059907922a
1a2921fcedb1d280ae6f27a871687199a1476d41
