### ISSUE TITLE
SortGeoData() fails with branches between independent basins

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#36]
independent basins are basins with separate outlets from the domain. If such basins are connected by branches, the result will contain duplicates.
This because SortGeoData identifies all outlet basins and sorts them independently atm. 
Connected basins should be combined before sorting.

**Comment by rcapell** [comment]
solved in latest commit.

**Comment by rcapell** [comment]
still does not work. Arctic-HYPE testcase: fails in SUBID 1074675, downstream SUBID 1075001.

**Comment by dgustafsson** [comment]
any updates on this issue? I have a new example, when I try to introduce branching in the outlet of the Danube. Sending files per email.

**Comment by dgustafsson** [comment]
what does you mean in your first comment: "Connected basins should be combined before sorting."?

**Comment by dgustafsson** [comment]
In my case, I can probably get around the problem by sorting teh geodata in two pieces. One without the subbasins in the smaller branch, and one with the basins on the main branch.

**Comment by rcapell** [comment]
No updates yet, I have not worked on this after Kristina solved this for ArcticHYPE on her own.

With the connected basins I mean that basins which are connected by a branch should be combined before the sorting iteration. I solved this by giving their respective outlet sub-basins a common downstream subid. But this did not work for all cases, e.g. the Arctic one.

There might be a problem with multiple branch connections between basins, but I have to look at the current code in detail. I remember that I thought about cirkular connections, and how that would influence sorting. I think HYPE technically allows impossible branchings, eg:
![imposssible_branching](https://cloud.githubusercontent.com/assets/6536193/22472212/3b4118b6-e7d5-11e6-9621-7cf22c8c3919.png)


I cannot see how this would impact on UpstreamGeoData.

**Comment by rcapell** [comment]
Probably solved. Closing for now.
