### ISSUE TITLE
change class HypeXobs to HypeObs

### ISSUE THREAD

**Issue by rcapell** [rcapell/HYPEtools#45]
... and adapt HypePTQobs to import as that.

**Comment by Nicole-X** [comment]
Hi, i met this question:
when i read demo file Pobs.txt using this code‘ReadXobs(filename = "Pobs.txt")
’，console return Warning messages: 1: In ReadXobs(filename = "Pobs.txt") :
  Duplicated variable-SUBID combination(s) in file: 1.35_0 1.41_0 1.41_0 1.45_0 1.32_0 1.33_0
2: In ReadXobs(filename = "Pobs.txt") :
  Imported as data frame, not as 'HypeXobs' object.
Does this have any effect on the running model，should i do something to eliminate this Warning?
Thank you for you time!

**Comment by c-brendel** [comment]
Hi!

I think the format of the Xobs.txt files is a bit different than the other obs files, so you should read the Pobs.txt file using the ReadObs() function. Do you get any warning messages if you use this function instead?

Conrad
