### ISSUE TITLE
how to install modified source code

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/HYPEtools#51]
Hi Rene,
excellent job on the wiki and change to HYPEtools!

I wonder, if I make a modification in the source code, can I also install these in my HYPEtools library? For instance, I am writing a new function ExtractObs (based on some code from UpstreamObs) including a new R file and a modified fortran library. How would I do to install these in my HYPEtools library? Maybe you showed me already, but I forgot...

**Comment by dgustafsson** [comment]
btw, if you compile the fortran file with the compiler available from Rtools, which command do you use? from the R console?
/David

**Comment by rcapell** [comment]
Regarding the compiler: 
The fortran code is compiled together with the package, the command is:

Rcmd.exe INSTALL --no-multiarch --with-keep.source HYPEtools
_or_
R CMD INSTALL --no-multiarch --with-keep.source HYPEtools

I can see the gfortran compile commands being executed through the above command:
gfortran -m64   -O2  -mtune=core2 -c  obsfile_handling.f90 -o obsfile_handling.o
gfortran -m64 -shared -s -static-libgcc -o HYPEtools.dll tmp.def obsfile_handling.o -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.5/bin/x64 -lR

**Comment by rcapell** [comment]
Regarding your first comment: 

Good to hear about ExtractObs(), I had been thinking about that but never got to actually do it. UpstreamObs() is somewhat deprecated because there are HYPE output variables for that now.

To integrate that into HYPEtools, i recommend you start an RStudio package project based on the current sources. Ideally, you could work in a git branch so we can integrate it in the main code when the function is ready. I don't know all the technical details on how to do that yet, we would have to check it out...
As an alternative to a branch within this repository, you could also clone it and send a pull request later. Again, something I have not done yet.

**Comment by dgustafsson** [comment]
so you mean I create a "RStudio package project" locally on my system using the current sources. Should I just keep the folder structure etc as it comes when downloading the source (HYPETools_master)?

**Comment by dgustafsson** [comment]
do you have Git installed? If I would have that, RStudio has some function to clone a project from there

**Comment by dgustafsson** [comment]
anyway, I created the project, opened it and from the RStudio menues, Clean and Rebuild, it seem to work well, compiled, installed and so on, but my new function ExtractObs is not loaded.

==> Rcmd.exe INSTALL --preclean --no-multiarch --with-keep.source HYPEtools-master

* installing to library 'C:/R/library'
* installing *source* package 'HYPEtools' ...
** libs
gfortran -m64   -O2  -mtune=core2 -c  obsfile_handling.f90 -o obsfile_handling.o
gfortran -m64 -shared -s -static-libgcc -o HYPEtools.dll tmp.def obsfile_handling.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/R/R-32~1.2/bin/x64 -lR
installing to C:/R/library/HYPEtools/libs/x64
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (HYPEtools)

**Comment by rcapell** [comment]
Functions need to be exported to be visible outside the package when it is loaded. This has to be declared in some package files. For HYPEtools, we use roxygen to take care of that. Roxygen works with tags in the function source files.

Here is what hopefully makes it work:

1. install roxygen2 library if you have not done that yet
2. go to Build => Configure Build Tools... => Build Tools (in new window); tick "Generate documentation with Roxygen" box (all boxes ticked in "Configure" pop-up)

3. add an export roxygen tag to your function:
    #' @export
=> check existing functions for examples on how to write roxygen-style documentation.

**Comment by dgustafsson** [comment]
Yes! It works after installing roxygen2. Now I just need to debug my function... btw, I based the function file on a previous function, so all the roxygen tags were there. Let you know when it works, so we can try how to get it back into the github version
