### ISSUE TITLE
EquallySpacedObs, unrealistic dates

### ISSUE THREAD

**Issue by julzab** [rcapell/HYPEtools#53]
Hello!

Just a small remark: When using the function _EquallySpacedObs_ and there are unrealistic dates in the data (e.g. 2007-02-31) the function throws the error message 

> Error in EquallySpacedObs(x = data2, timestep = "day") : 
>   Duplicated dates in 'x'.

Maybe in case of an unrealistic date the error message can be modified?
However, great functions! Thanks a lot for your efforts!

/Julia

**Comment by rcapell** [comment]
Do you try to pass character strings instead of dates to the function? Otherwise you would have gotten the error earlier whe nconverting to dates, e.g.:
```
> as.POSIXct("2007-02-21")
[1] "2007-02-21 CET"
> as.POSIXct("2007-02-31")
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
```
I never meant for the function to work with strings but maybe it does anyway? I will have a look at it!

**Comment by julzab** [comment]
Hi!

Unfortunately, I cannot repoduce the error.  But, I used 
`as.Date(paste( month_day_Q2$year , month_day_Q2$month, month_day_Q2$day , sep = "-" )  , format = "%Y-%m-%d" )`
to produce a  date first . For an unrealistic date a NA is produced (same if "as.POSIXct" is used) . Using the EquallySpacedObs function on a data frame containing this kind of dates results in the error message:

> Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite

which is more logical to me than the other error message (however this was produced....)

**Comment by rcapell** [comment]
Ok. I rephrased the help to make it more clear, and added an error condition which stops the function with message "NAs in date-time column of 'x'.".
Closing this issue for now.
