### ISSUE TITLE
help for GW retention

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#56]
Couple corrections there:
"lr is rural load into soil layer 3" ... lr is rural load (total from geodata converted to kg/yr; locsoil in the formula converts it to rural load into soil layer 3)

"GwRetention returns a two-column data frame, with SUBIDs and retention in groundwater (kg/y)."
Retention is a proportion (dimensionless); if multiplied by 100, it becomes %.

**Comment by rcapell** [comment]
Thanks, done!
