### ISSUE TITLE
error in PlotBasinSummary: could not find function "mpp"

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#57]
Error occurs only with the log option, possibly due to zeros in observed concentrations
[9545022.txt](https://github.com/rcapell/HYPEtools/files/526473/9545022.txt)

**Comment by rcapell** [comment]
Thanks! 
Fixed it, was a typo to begin with, and then some NA treatment that was missing. Code now also handles the (probably rare) case that there are only zero-concentrations in a plotted variable in combination with log-scaled axes.
