### ISSUE TITLE
PlotBasinSummary fails

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#58]
I get the following error when I run PlotBasinSummary with the attached file:

Error in plot.window(...) : need finite 'xlim' values
[9000887.txt](https://github.com/rcapell/HYPEtools/files/610844/9000887.txt)

**Comment by rcapell** [comment]
hm, I can't reproduce that. What options do you use?

**Comment by a753bart** [comment]
I can send you the info tomorrow once I get back from the MIRACLE meeting. It's the log option from the v3 script. There were couple other subids with the same error.

Are you back in the office today? If so, can you email me what we decided on the climate scenarios? I forgot to take my paper notes from the office on Friday

Alena

Sent from my iPhone

On 28 Nov 2016, at 10:01, rcapell <notifications@github.com<mailto:notifications@github.com>> wrote:


hm, I can't reproduce that. What options do you use?

**Comment by rcapell** [comment]
Fixed. This occurred in concentration ratios (in this case SP/TP), if there were no concurrent observations and the ratio vector contained only NA values.
