### ISSUE TITLE
25th percentile band outside min-max band in PlotBasinSummary

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#61]
I think it happens due to zeros in the results and a log scale? It seems that for SP, the exceedance curve includes the zeros also, not that the simulated line goes only to 0.99. 

The real solution I guess should be to increase the accuracy of the results :) but maybe the function can print out a warning or something (on the chart or on the screen with subid number) and not print the band for months with zeros. The resulting chart just looks strange.

[0000045.txt](https://github.com/rcapell/HYPEtools/files/677117/0000045.txt)

See SP and SP/TP in the attached plot.

![plot_0000045_bassum_log_res_all_adj](https://cloud.githubusercontent.com/assets/20319028/21544574/7f3c2cdc-cdd0-11e6-9f1d-17e5f267765c.png)

**Comment by a753bart** [comment]
I increased the decimals from 3 to 5; that helped for some months but not for all .
![plot_0000045_bassum_log_res_all_adj2](https://cloud.githubusercontent.com/assets/20319028/21545999/1fe8f1e6-cddc-11e6-81eb-745f1960481b.png)

**Comment by c-brendel** [comment]
I added some code to PlotSimObsRegime() to filter out negative/zero values before generating the polygons.
```
bo <- ReadBasinOutput("0000045.txt")
PlotBasinSummary(x = bo, panels = 2, log = T)
```
