### ISSUE TITLE
Problems using ReadTimeOutput

### ISSUE THREAD

**Issue by cshell79** [rcapell/HYPEtools#62]
Using ReadTimeOutput gives the following error:

Error in setcolorder(ans, reorder) : 
  neworder is length 0 but x has 35409 columns

The workaround is to give the function the a vector with all the columns in the argument "select"

**Comment by rcapell** [comment]
Thanks!

This is already fixed in 8f0ecfc. Relates to how the default value for "select" is handled in latest data.table release. I reported a bug there, and implemented a workaround in HYPEtools. 

I will compile a new release shortly!
