### ISSUE TITLE
CleanSLCClasses() gives negative values

### ISSUE THREAD

**Issue by moravecv** [rcapell/HYPEtools#67]
When used **CleanSLCClasses()** it gives negative values to those which are under the threshold and are supposed be transferred to different classes.

**Comment by rcapell** [comment]
Can you provide:
1) the function command as you used it
2) all helper text files for method 1, if you used that

thanks!

**Comment by moravecv** [comment]
The function command:

`gd1 = CleanSLCClasses(gd = gd, gc = gc, m1.file = "transfer_slc.txt", m1.class = "landuse", m1.clean = c(T,T), progbar = T)`

while the **transfer_slc.txt** file looks like this:
[transfer_slc.txt](https://github.com/rcapell/HYPEtools/files/987197/transfer_slc.txt)

**Comment by rcapell** [comment]
Input GeoData already contained negative numbers...
