### ISSUE TITLE
WriteMapOutput daily timesteps

### ISSUE THREAD

**Issue by julzab** [rcapell/HYPEtools#77]
Hi!
When I use WriteMapOutput with a Daily timestep, spaces are created before the comma.

Please see the example file (read it in, Write MapOutput)

Cheers,

Julia
[mapCTMP.txt](https://github.com/rcapell/HYPEtools/files/1543655/mapCTMP.txt)

**Comment by rcapell** [comment]
This is a combination of a garbled header in your file, after 1986-12-26, and that the function did not check if dates in the date attribute are strings or POSIX dates.

I updated the function with a check for that, but it still expects accurate headers. :)
