### ISSUE TITLE
parreg proportion for upstream catchments

### ISSUE THREAD

**Issue by diafu** [rcapell/HYPEtools#86]
Hi, I am guessing that there is not a function that estimates parreg proportion for each catchment?

**Comment by rcapell** [comment]
That is correct. If you like to see that, please provide a few more details on what you expect the function to return. :)

**Comment by diafu** [comment]
Thanks for your answer. I am expecting to obtain the upstream area-weighted average for the parreg value, as for example is done for all SLC classes in the function UpstreamGeoData . Thanks!
