### ISSUE TITLE
ReadGeoClass failure

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/HYPEtools#87]
The ReadGeoClass fails when the number of soil layers is less than the most commonly used 3 layers. The function expects at least 14 columns, which requires 3 soildepth columns.

However, HYPE can be setup with 1 or 2 layers as well, so the number of columns in the GeoClass file can be 12 or 13 as well.

A complication is now the new feature to read inline comments after the final soildepth column. So actually, the function first need to check the number of columns with numerical data, and then look for inline comments. 

Here is a suggestion for ReadGeoClass (I guess something might be required also in WriteGeoClass?).

[ReadGeoClassNew.txt](https://github.com/rcapell/HYPEtools/files/2325769/ReadGeoClassNew.txt)

Sample files attached as well.
[GeoClass.txt](https://github.com/rcapell/HYPEtools/files/2325767/GeoClass.txt)
[GeoClass-with-comment-and-2-soil-layers.txt](https://github.com/rcapell/HYPEtools/files/2325768/GeoClass-with-comment-and-2-soil-layers.txt)

**Comment by dgustafsson** [comment]
actually, the check for number of data columns must be minimized to 14 - all other columns should be considered as comments even if they are numeric. My solution will also fail if there is for instance 13 GeoClass data columns followed by one non-numeric column and then again another numeric column. A safer method would be to check each column one-by-one from left to right, and assume that the first non-numeric column (before column 15) marks the end of the real GeoClass data.

**Comment by rcapell** [comment]
Thanks for report, example files, and suggested solution! :smiley:

I opted for an if-else tree, to catch the possible combinations of data and comment columns. The one case that is not explicitly accounted for is a numeric comment in column 13 or 14 (depth2, depth3). But I think this would throw off HYPE anyway...

Closing for now, pls re-open if it doesn't work for you!
