### ISSUE TITLE
PlotBasinOutput: plotting of precipitation

### ISSUE THREAD

**Issue by diafu** [rcapell/HYPEtools#90]
Hi, it looks like if there is something weird with the plotting of precipitation in the PlotBasinOutput function, one can roughly see the precipitation. My plot is at the hourly scale. I have plotted the data in another program and it does not look like that.
 
Thanks!

![hype_tools_fig](https://user-images.githubusercontent.com/36507717/46132894-94348c00-c23f-11e8-9869-8f6d703b0d95.jpeg)

**Comment by rcapell** [comment]
[0018149.txt](https://github.com/rcapell/HYPEtools/files/3545845/0018149.txt)

Your example file, attached here for reference.
The file contains '-9188.805' values in columns upcpSF and upcprc, which ReadBasinOutput() does not handle as empty value on import.

Do you know where these values come from, are they errors in the Pobs file, or artefacts of the hourly HYPE run?

**Comment by rcapell** [comment]
Otherwise, I think the precip bars in the plot become so thin with the hourly resolution that they are rendered invisible. I try and find a solution for that.

**Comment by rcapell** [comment]
Solved, should work now even for many time steps.
