### ISSUE TITLE
Missing values in basin output / plot basin output

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#92]
Both PlotBasinOutput and PlotBasinSummary now treat -9999 as an actual number instead of recognizing it's a missing value. The basin output dataframe also contains -9999. 

script:

bas<-ReadBasinOutput(paste0(pth.res,subbas,".txt"))
  
  PlotBasinSummary(bas, filename = paste0(pth.out,"plots/", "plot_",subbas,"_BasSum"), panels = 1, gd = hgd,
                   bd = hbd, gcl = hgc, psd = hpsd, subid = attr(bas,"subid"), desc = hdesc,
                   timestep = attr(bas, "timestep"), hype.vars = "all", from = 1,
                   to = nrow(bas), log = FALSE, xscale = "gauss", start.mon = 10)
  
  PlotBasinOutput(bas, filename = paste0(pth.out,"plots/","plot_",subbas,"_BasOut"), timestep = attr(bas, "timestep"),
                  hype.vars = "all", vol.err = T, log.q = F, start.mon = 1, from = 1,
                  to = nrow(bas), name = paste0(subbas), area = NULL, subid = attr(bas, "subid"),
                  gd = hgd, bd = hbd)

[9000852.txt](https://github.com/rcapell/HYPEtools/files/3223649/9000852.txt)

![plot_9000852_BasOut](https://user-images.githubusercontent.com/20319028/58418714-d80aba00-8088-11e9-8b34-9e9d0475b4cb.png)
![plot_9000852_BasSum_log_](https://user-images.githubusercontent.com/20319028/58418724-dc36d780-8088-11e9-8a14-4bb15d5dcf27.png)

**Comment by rcapell** [comment]
Side effect of variation in HYPE output with "signfigures" option in info.txt. 
Fixed.
