### ISSUE TITLE
Append when writing obs-files

### ISSUE THREAD

**Issue by dgustafsson** [rcapell/HYPEtools#96]
I made a modification of WritePTQobs to be able to append to existing files - it was necessary when producing a long time series (>30yrs) for a large model setup (>30000 subbasins). Maybe it could be included in any of the write-to-obsfile-functions?

[WritePTQObsAppend.R.txt](https://github.com/rcapell/HYPEtools/files/3782376/WritePTQObsAppend.R.txt)

**Comment by rcapell** [comment]
Thanks David!
I will look at it and get back to you if questions arise. Any need to have this included at a deadline? The earliest I can work on this is in 2 weeks time if it doesn't need to get high prio.
